### ISSUE TITLE
XPS 15 9570 4K i7 8750H

### ISSUE THREAD

**Issue by kevinshroff** [shenlinsl/DELL-XPS-15-9570-8950-4K-macOS-Mojave#3]
Hi, does sleep work with your EFI? Any issues with sleep?

**Comment by shenlinsl** [comment]
My equipment sleeps well.

**Comment by kevinshroff** [comment]
Sleep with lid close or sleep by menu bar doesn't work for me - when I wake the machine it has a black screen. I have the XPS 15 9570 16GB RAM 4K i7 8750H.

EDIT: Sleep works with config15.2, however there is no brightness adjustment.
